version: 2.1
executors:
    default:
        docker:
            - image: cimg/node:lts
        working_directory: ~/repo
jobs:
    test:
        executor: default
        steps:
            - checkout
            - restore_cache:
                key: node_modules-2-{{ checksum "package.json" }}-{{ checksum "package-lock.json"}}
            - run: npm ci
            - save_cache:
                paths:
                    - $HOME/.npm
                key: node_modules-2-{{ checksum "package.json" }}-{{ checksum "package-lock.json"}}
            # ログディレクトリの作成
            - run:
                command: |
                    mkdir -p results
                    mkdir -p results/eslint
            - run:
                name: eslint
                command: npm run eslint -- --format=html -o ./results/eslint/eslint.html
            - run:
                name: Run tests
                command: npm run test:ci
            - store_test_results:
                path: results
            - store_artifacts:
                path: results
workflows:
    version: 2
    workflow:
        jobs:
            - test
